name: Release

on:
  push:
    tags:
      - v*
  workflow_run:
    workflows: ["Cmake"]
    branches: [main]
    types: 
      - completed


jobs:
  release:
    name: Release pushed tag
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    needs: Cmake
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Release Artifacts
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes release/